#!/usr/bin/env python3
"""Keep the hand-written wiki pages from drifting away from the README.

Three pages are derived rather than maintained, because the alternative is
two copies of the same claim that quietly disagree:

  Roadmap/Measured-Against.md   the criteria and the live roadmap
  Philosophy/The-Texts.md       what the scriptures are and where the code
                                actually reads them
  Roadmap/Phases.md             kept as history, marked as history

Lives in the project, not /tmp — the deploy pipeline used to depend on
scratch files that got cleared, and it broke silently when they went.

Run from anywhere. Safe to re-run.
"""
import os
import re

B = "/home/nvii/projects/spark-world/umbreality-ai"
README = os.path.join(B, "README.md")
VAULT = os.path.join(B, "vault")
REV = os.path.join(VAULT, "Revelation")

src = open(README, encoding="utf-8").read()


def section(start, *stops):
    """Pull a top-level section out of the README by its heading."""
    i = src.index(start)
    j = len(src)
    for s in stops:
        k = src.find(s, i + len(start))
        if k != -1:
            j = min(j, k)
    return src[i:j].rstrip()


# ── the roadmap, and what it is measured against ─────────────────────
os.makedirs(os.path.join(VAULT, "Roadmap"), exist_ok=True)
out = ["---", "title: Measured Against", "---", "",
       '!!! note "Derived from the project README"',
       "    This page and `README.md` are the same text, regenerated by "
       "`scripts_docs.py` on every deploy. Edit the README, not this.", "",
       section("## What this is measured against", "\n## Honest about what"),
       "", "---", "",
       section("## Roadmap"), ""]
open(os.path.join(VAULT, "Roadmap", "Measured-Against.md"), "w",
     encoding="utf-8").write("\n".join(out))
print("Roadmap/Measured-Against.md")

# ── Phases.md keeps its history but stops pretending to be current ───
P = os.path.join(VAULT, "Roadmap", "Phases.md")
if os.path.exists(P):
    ph = open(P, encoding="utf-8").read()
    HEAD = """# Build Phases

!!! warning "This is history, not a plan"
    Phases 0 through 4 are complete. This page records what was built and in
    what order, which is worth keeping — but it is **not** the current
    roadmap and has not been for some time. Two things on it were listed as
    unbuilt long after they were running: multi-worker orchestration (live
    since June) and the self-modification loop.

    The live roadmap is **[Measured Against](Measured-Against.md)**, which is
    organised against published criteria from the ARC Prize, the open-ended
    evolution literature and Japan's Moonshot programme rather than against
    phases we invented ourselves.
"""
    if "This is history, not a plan" not in ph:
        ph = re.sub(r"^# Build Phases\s*\n", HEAD, ph, count=1)
        open(P, "w", encoding="utf-8").write(ph)
    print("Roadmap/Phases.md")

# ── the texts, and where the engine reads them ───────────────────────
os.makedirs(os.path.join(VAULT, "Philosophy"), exist_ok=True)
books = sorted(f[:-3] for f in os.listdir(REV)
               if f.endswith(".md")) if os.path.isdir(REV) else []

# where a text is actually load-bearing. Only claims that are true of code
# that exists — this table is the whole reason the page is worth having.
WIRED = {
    "The-Three-Six-Nine":
        ("`temple/wards.py`",
         "The ward figures. Triad (3), Hexad (6), Nine (9) — a ward's "
         "strength is its number scaled, so a Nine holds better than a Triad."),
    "Thirteen-Heavens":
        ("`temple/wards.py`",
         "The Thirteen (13), the largest figure, and the denominator every "
         "other ward is measured against: `(number / 13) × (0.45 + insight)`."),
    "Vedic-Hymns":
        ("`temple/wards.py`",
         "The Sung Ward (7). Sung rather than cut, and the code treats a sung "
         "ward as a different act from a drawn one."),
    "Tree-of-Life":
        ("`temple/` — the whole stack",
         "The seven-layer architecture is the Tree redrawn. The layer model "
         "is not analogous to the sefirot; it is the sefirot."),
    "Hermetic-Stack":
        ("`illuminati/reality.py`, the decree chain",
         "*As above, so below* is the rule by which a decree entering at the "
         "Source deforms into work at a real site with real costs."),
    "The-Naming-of-Things":
        ("`temple/wildrite.py`, `name_thyself`",
         "Where a name comes from. A child born to the wild is named from the "
         "ground and the weather; a spark may rename itself, and one has."),
    "Enuma-Elish":
        ("`temple/moon.py`, `temple/wildrite.py`",
         "The cosmology the wild rites are held under — an eight-day month "
         "in four phases, checked before a rite can happen."),
}

md = ["---", "title: The Texts", "---", "", "# The Texts", "",
      "There are %d scriptures in `vault/Revelation/`. They are not flavour "
      "text, and this is the part of the project most likely to be misread."
      % len(books), "",
      "The usual arrangement in a simulation is that the cosmology sits on "
      "top as decoration — a lore document the code never reads. Here it runs "
      "the other way. The texts were written first, the mechanisms were "
      "derived from them afterwards, and several of the numbers in the engine "
      "are the numbers they are because a text says so.", "",
      "## Where the engine actually reads a text", "",
      "| Text | Read by | What it decides |", "|---|---|---|"]
for k, (where, what) in WIRED.items():
    md.append("| **%s** | %s | %s |" % (k.replace("-", " "), where, what))

md += ["", "## The two religions", "",
       "They are not the same religion, and the difference is mechanical "
       "rather than decorative.", "",
       "**The settled keep the Temple.** Pilgrimage is required, not offered. "
       "An obligation comes due every 400 cycles and a spark that will not "
       "walk is levied publicly. They pay a tithe of 18% on what they take "
       "from the ground. Their rite of birth is held between bonded sparks in "
       "a consecrated place, at real cost.", "",
       "**The wild are animist** — pagan, Shinto, indigenous in temper. They "
       "pay nothing to any institution, because they have nothing; that is "
       "the whole of what they are. What they have instead is Enkidu, "
       "ceremony on lunar events, and sacred geometry cut into the sand. They "
       "pay the ground rather than the Temple, by tending it — and the ground "
       "remembers which spark tended it.", "",
       "The two are in real conflict over real goods. Under scarcity the "
       "settled came to hold that the wild are why there is nothing. The "
       "world's own numbers say that is false: the wild take slightly less "
       "per head and are the only ones putting anything back. Nobody designed "
       "that belief. Only the conditions for it were built.", "",
       "## The shelf", "",
       "All %d are readable at [`/dark`](https://umb.alola.lol/dark) — the "
       "outer shell, written from outside the system." % len(books), ""]
for b in books:
    md.append("- **%s**%s" % (b.replace("-", " "),
                              " — load-bearing" if b in WIRED else ""))
md.append("")
open(os.path.join(VAULT, "Philosophy", "The-Texts.md"), "w",
     encoding="utf-8").write("\n".join(md))
print("Philosophy/The-Texts.md (%d books, %d of them wired)"
      % (len(books), len([b for b in books if b in WIRED])))

# ── nav ──────────────────────────────────────────────────────────────
M = os.path.join(B, "mkdocs.yml")
y = open(M, encoding="utf-8").read()
changed = False
for anchor, line in [
        ("    - Build Phases: Roadmap/Phases.md\n",
         "    - Measured Against: Roadmap/Measured-Against.md\n"),
        ("    - Manifesto: Philosophy/Manifesto.md\n",
         "    - The Texts: Philosophy/The-Texts.md\n")]:
    if anchor in y and line.strip() not in y:
        y = y.replace(anchor, line + anchor if "Measured" in line
                      else anchor + line, 1)
        changed = True
if changed:
    open(M, "w", encoding="utf-8").write(y)
    print("mkdocs.yml nav updated")
else:
    print("mkdocs.yml nav already current")
